=pod

=encoding utf8

=head1 NAME

LWP::Protocol::Net::Curl - the power of libcurl in the palm of your hands!

=head1 VERSION

version 0.001

=head1 SYNOPSIS

    #!/usr/bin/env perl;
    use common::sense;
    use WWW::Mechanize;
    use LWP::Protocol::Net::Curl;
    ...

=head1 DESCRIPTION

...

=for Pod::Coverage import
request

=head1 SEE ALSO

=over 4

=item *

L<LWP::Coro>

=item *

L<LWP::Protocol::AnyEvent::http>

=item *

L<Net::Curl>

=back

=head1 AUTHOR

Stanislaw Pusep <stas@sysd.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Stanislaw Pusep.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

